name: Docker Validation

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: jared7/kickthemount:latest

      - name: Validate Docker Bake
        uses: docker/bake-action@v5
        with:
          files: docker-bake.hcl
